#Configuratio initiale
GRID_SIZE= 30
INITIAL_SHEEP=50
INITIAL_WOLVES=10
INITIAL_GRASS_COVERAGE=0.3

#Energie
SHEEP_INITIAL_ENERGY=20
WOLF_INITIAL_ENERGY=40
SHEEP_ENERGY_FROM_GRASS=15
WOLF_ENERGY_FROM_SHEEP=35
SHEEP_ENERGY_LOSS_PER_TURN=1
WOLF_ENERGY_LOSS_PER_TURN=2

#Reproduction
SHEEP_REPRODUCTION_THRESHOLD=50
WOLF_REPRODUCTION_THRESHOLD=80
REPRODUCTION_ENERGY_COST=20

#Age
SHEEP_MAX_AGE=50
WOLF_MAX_AGE=40

#herbe
GRASS_GROWTH_PROBABILITY=0.08
GRASS_REGRWTH_TIME=7

#Simulation
MAX_TURNS=500
