#Configuratio initiale
GRID_SIZE= 30
INITIAL_SHEEP=50
INITIAL_WOLVES=10
INITIAL_GRASS_COVERAGE=0.3

#Energie
SHEEP_INITIAL_ENERGY=20
WOLF_INITIAL_ENERGY=40
SHEEP_ENERGY_FROM_GRASS=15
WOLF_ENERGY_FROM_SHEEP=35
SHEEP_ENERGY_LOSS_PER_TURN=1
WOLF_ENERGY_LOSS_PER_TURN=2
