#Configuratio initiale
GRID_SIZE= 30
INITIAL_SHEEP=20
INITIAL_WOLVES=5
INITIAL_GRASS_COVERAGE=0.3

#Energie
SHEEP_INITIAL_ENERGY=20
WOLF_INITIAL_ENERGY=40
SHEEP_ENERGY_FROM_GRASS=15
WOLF_ENERGY_FROM_SHEEP=35
SHEEP_ENERGY_LOSS_PER_TURN=5
WOLF_ENERGY_LOSS_PER_TURN=5

#Reproduction
SHEEP_REPRODUCTION_THRESHOLD=70
WOLF_REPRODUCTION_THRESHOLD=100
REPRODUCTION_ENERGY_COST=50

#Age
SHEEP_MAX_AGE=25
WOLF_MAX_AGE=20

#herbe
GRASS_GROWTH_PROBABILITY=0.08
GRASS_REGROWTH_TIME=7

#Simulation
MAX_TURNS=500
